- name: Demo on Variables
  hosts: all
  vars:
     URL1: play.google.com
  vars_files:
    - vars.yml
  tasks: 
    - name: Print a Variable play
      debug:
        msg: URL = {{URL1}}
    - name: Print a  Varible from file
      debug:
        msg: URL = {{URL2}}