- name: Demo on Variables
  hosts: all
  vars:
     URL1: play.google.com
     URL:  play.google.com
  vars_files:
    - vars.yml
  tasks: 
    - name: Print a Variable play
      debug:
        msg: URL = {{URL1}}
    - name: Print a  Varible from file
      debug:
        msg: URL = {{URL2}}
    - name: Demo on task level variable
      vars:
         URL3: tasks.google.com
      debug:
        msg: URL = {{URL3}}
    - name: Print Variables from Host file
      debug:
        msg: URL = {{URL4}}
    - name: Print variables from CLi
      debug:
        msg: URL = {{URL5}}
    - name: Demo on Precendence
      vars:
         URL:  tasks.google.com
      debug:
        msg: URL = {{URL}}
    - name: print Fact variable
      debug:
        msg: OS = {{ansible_distribution}}
    - name: Run a shell command and store output
      shell: uptime
      register: out
    - name: print uptime output
      debug:
        msg: "{{out.stdout}}"
    - name: Declare a variable/fact
      set_fact:
         OUTPUT: "{{out.stdout}}"

    - name: Print OUTPUT
      debug:
        msg: "{{OUTPUT}}"  
      
    - roles:
        -demo: